from typing import overload

class Date:
    _year: int
    _month: int
    _day: int
    @overload
    def __init__(self, year:int, month:int, day:int) -> None: ...
    @overload
    def __init__(self, year:str, month:str, day:str) -> None: ...
    def __str__(self) -> str: ...
    def year(self) -> int: ...
    def month(self) -> int: ...
    def day(self) -> int: ...
    @staticmethod
    def today() -> Date: ...

